version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/website'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pip'
    directory: '/puppeteer'
    schedule:
      interval: 'weekly'
